# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: checkpointconfigurations.checkpointing.gke.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: checkpointing.gke.io
  # list of versions supported by this CustomResourceDefinition
  versions:
  - name: v1
    # Each version can be enabled/disabled by Served flag.
    served: true
    # One and only one version must be marked as the storage version.
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              cloudStorageBucketName:
                type: string
              enableExternalJaxProcessIds:
                type: boolean
              nodeSelector:
                type: object
                additionalProperties:
                  type: string
              tolerations:
                type: array
                items:
                  type: object
                  properties:
                    key:
                      type: string
                    operator:
                      type: string
                    effect:
                      type: string
                    tolerationSeconds:
                      type: integer
                    value:
                      type: string
              inMemoryVolumeSize:
                type: string
              csiEphemeralLimit:
                type: string
              gcsFuseMountOptions:
                type: array
                items:
                  type: string
          status:
            type: object
            properties:
              # instanceHandle is in the form of projects/PROJECT/locations/LOCATION/instances/INSTANCE_NAME
              instanceHandle:
                type: string
              error:
                type: string
    # subresources for the custom resource
    subresources:
      # enables the status subresource
      status: {}
  # either Namespaced or Cluster
  scope: Cluster
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: checkpointconfigurations
    # singular name to be used as an alias on the CLI and for display
    singular: checkpointconfiguration
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: CheckpointConfiguration
    # shortNames allow shorter string to match your resource on the CLI
    listKind: CheckpointConfigurationList
    shortNames:
    - cpc
