/*
Copyright Google 2025

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	context "context"
	time "time"

	apischeckpointinggkeiov1 "gke-internal.googlesource.com/gke-storage/high-scale-checkpointing/apis/checkpointing.gke.io/v1"
	versioned "gke-internal.googlesource.com/gke-storage/high-scale-checkpointing/lib/client/clientset/versioned"
	internalinterfaces "gke-internal.googlesource.com/gke-storage/high-scale-checkpointing/lib/client/informers/externalversions/internalinterfaces"
	checkpointinggkeiov1 "gke-internal.googlesource.com/gke-storage/high-scale-checkpointing/lib/client/listers/checkpointing.gke.io/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CheckpointConfigurationInformer provides access to a shared informer and lister for
// CheckpointConfigurations.
type CheckpointConfigurationInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() checkpointinggkeiov1.CheckpointConfigurationLister
}

type checkpointConfigurationInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCheckpointConfigurationInformer constructs a new informer for CheckpointConfiguration type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCheckpointConfigurationInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCheckpointConfigurationInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCheckpointConfigurationInformer constructs a new informer for CheckpointConfiguration type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCheckpointConfigurationInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CheckpointingV1().CheckpointConfigurations(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CheckpointingV1().CheckpointConfigurations(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CheckpointingV1().CheckpointConfigurations(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CheckpointingV1().CheckpointConfigurations(namespace).Watch(ctx, options)
			},
		},
		&apischeckpointinggkeiov1.CheckpointConfiguration{},
		resyncPeriod,
		indexers,
	)
}

func (f *checkpointConfigurationInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCheckpointConfigurationInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *checkpointConfigurationInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apischeckpointinggkeiov1.CheckpointConfiguration{}, f.defaultInformer)
}

func (f *checkpointConfigurationInformer) Lister() checkpointinggkeiov1.CheckpointConfigurationLister {
	return checkpointinggkeiov1.NewCheckpointConfigurationLister(f.Informer().GetIndexer())
}
