// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/replication.proto

package replication

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RegisterCoordinator messages
type RegisterCoordinatorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobName       string                 `protobuf:"bytes,1,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterCoordinatorRequest) Reset() {
	*x = RegisterCoordinatorRequest{}
	mi := &file_proto_replication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterCoordinatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCoordinatorRequest) ProtoMessage() {}

func (x *RegisterCoordinatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCoordinatorRequest.ProtoReflect.Descriptor instead.
func (*RegisterCoordinatorRequest) Descriptor() ([]byte, []int) {
	return file_proto_replication_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterCoordinatorRequest) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *RegisterCoordinatorRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type RegisterCoordinatorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterCoordinatorResponse) Reset() {
	*x = RegisterCoordinatorResponse{}
	mi := &file_proto_replication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterCoordinatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCoordinatorResponse) ProtoMessage() {}

func (x *RegisterCoordinatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCoordinatorResponse.ProtoReflect.Descriptor instead.
func (*RegisterCoordinatorResponse) Descriptor() ([]byte, []int) {
	return file_proto_replication_proto_rawDescGZIP(), []int{1}
}

// GetCoordinator messages
type GetCoordinatorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobName       string                 `protobuf:"bytes,1,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoordinatorRequest) Reset() {
	*x = GetCoordinatorRequest{}
	mi := &file_proto_replication_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoordinatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoordinatorRequest) ProtoMessage() {}

func (x *GetCoordinatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoordinatorRequest.ProtoReflect.Descriptor instead.
func (*GetCoordinatorRequest) Descriptor() ([]byte, []int) {
	return file_proto_replication_proto_rawDescGZIP(), []int{2}
}

func (x *GetCoordinatorRequest) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

type GetCoordinatorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoordinatorResponse) Reset() {
	*x = GetCoordinatorResponse{}
	mi := &file_proto_replication_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoordinatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoordinatorResponse) ProtoMessage() {}

func (x *GetCoordinatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoordinatorResponse.ProtoReflect.Descriptor instead.
func (*GetCoordinatorResponse) Descriptor() ([]byte, []int) {
	return file_proto_replication_proto_rawDescGZIP(), []int{3}
}

func (x *GetCoordinatorResponse) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

// UnregisterCoordinator messages
type UnregisterCoordinatorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobName       string                 `protobuf:"bytes,1,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterCoordinatorRequest) Reset() {
	*x = UnregisterCoordinatorRequest{}
	mi := &file_proto_replication_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterCoordinatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterCoordinatorRequest) ProtoMessage() {}

func (x *UnregisterCoordinatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterCoordinatorRequest.ProtoReflect.Descriptor instead.
func (*UnregisterCoordinatorRequest) Descriptor() ([]byte, []int) {
	return file_proto_replication_proto_rawDescGZIP(), []int{4}
}

func (x *UnregisterCoordinatorRequest) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *UnregisterCoordinatorRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type UnregisterCoordinatorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterCoordinatorResponse) Reset() {
	*x = UnregisterCoordinatorResponse{}
	mi := &file_proto_replication_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterCoordinatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterCoordinatorResponse) ProtoMessage() {}

func (x *UnregisterCoordinatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterCoordinatorResponse.ProtoReflect.Descriptor instead.
func (*UnregisterCoordinatorResponse) Descriptor() ([]byte, []int) {
	return file_proto_replication_proto_rawDescGZIP(), []int{5}
}

// SetReplicationPeer messages
type SetReplicationPeerRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LocalMountpoint string                 `protobuf:"bytes,1,opt,name=local_mountpoint,json=localMountpoint,proto3" json:"local_mountpoint,omitempty"`
	TargetIp        string                 `protobuf:"bytes,2,opt,name=target_ip,json=targetIp,proto3" json:"target_ip,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetReplicationPeerRequest) Reset() {
	*x = SetReplicationPeerRequest{}
	mi := &file_proto_replication_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetReplicationPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetReplicationPeerRequest) ProtoMessage() {}

func (x *SetReplicationPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetReplicationPeerRequest.ProtoReflect.Descriptor instead.
func (*SetReplicationPeerRequest) Descriptor() ([]byte, []int) {
	return file_proto_replication_proto_rawDescGZIP(), []int{6}
}

func (x *SetReplicationPeerRequest) GetLocalMountpoint() string {
	if x != nil {
		return x.LocalMountpoint
	}
	return ""
}

func (x *SetReplicationPeerRequest) GetTargetIp() string {
	if x != nil {
		return x.TargetIp
	}
	return ""
}

type SetReplicationPeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetReplicationPeerResponse) Reset() {
	*x = SetReplicationPeerResponse{}
	mi := &file_proto_replication_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetReplicationPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetReplicationPeerResponse) ProtoMessage() {}

func (x *SetReplicationPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetReplicationPeerResponse.ProtoReflect.Descriptor instead.
func (*SetReplicationPeerResponse) Descriptor() ([]byte, []int) {
	return file_proto_replication_proto_rawDescGZIP(), []int{7}
}

// MountGCSBucket messages
type MountGCSBucketRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LocalMountpoint string                 `protobuf:"bytes,1,opt,name=local_mountpoint,json=localMountpoint,proto3" json:"local_mountpoint,omitempty"` // Add optional fields here for future credentials or bucket specification
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MountGCSBucketRequest) Reset() {
	*x = MountGCSBucketRequest{}
	mi := &file_proto_replication_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountGCSBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountGCSBucketRequest) ProtoMessage() {}

func (x *MountGCSBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountGCSBucketRequest.ProtoReflect.Descriptor instead.
func (*MountGCSBucketRequest) Descriptor() ([]byte, []int) {
	return file_proto_replication_proto_rawDescGZIP(), []int{8}
}

func (x *MountGCSBucketRequest) GetLocalMountpoint() string {
	if x != nil {
		return x.LocalMountpoint
	}
	return ""
}

type MountGCSBucketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountGCSBucketResponse) Reset() {
	*x = MountGCSBucketResponse{}
	mi := &file_proto_replication_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountGCSBucketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountGCSBucketResponse) ProtoMessage() {}

func (x *MountGCSBucketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountGCSBucketResponse.ProtoReflect.Descriptor instead.
func (*MountGCSBucketResponse) Descriptor() ([]byte, []int) {
	return file_proto_replication_proto_rawDescGZIP(), []int{9}
}

// UnmountPeer messages
type UnmountPeerRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LocalMountpoint string                 `protobuf:"bytes,1,opt,name=local_mountpoint,json=localMountpoint,proto3" json:"local_mountpoint,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UnmountPeerRequest) Reset() {
	*x = UnmountPeerRequest{}
	mi := &file_proto_replication_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmountPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmountPeerRequest) ProtoMessage() {}

func (x *UnmountPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmountPeerRequest.ProtoReflect.Descriptor instead.
func (*UnmountPeerRequest) Descriptor() ([]byte, []int) {
	return file_proto_replication_proto_rawDescGZIP(), []int{10}
}

func (x *UnmountPeerRequest) GetLocalMountpoint() string {
	if x != nil {
		return x.LocalMountpoint
	}
	return ""
}

type UnmountPeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmountPeerResponse) Reset() {
	*x = UnmountPeerResponse{}
	mi := &file_proto_replication_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmountPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmountPeerResponse) ProtoMessage() {}

func (x *UnmountPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmountPeerResponse.ProtoReflect.Descriptor instead.
func (*UnmountPeerResponse) Descriptor() ([]byte, []int) {
	return file_proto_replication_proto_rawDescGZIP(), []int{11}
}

// UnmountAllPeers messages
type UnmountAllPeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmountAllPeersRequest) Reset() {
	*x = UnmountAllPeersRequest{}
	mi := &file_proto_replication_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmountAllPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmountAllPeersRequest) ProtoMessage() {}

func (x *UnmountAllPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmountAllPeersRequest.ProtoReflect.Descriptor instead.
func (*UnmountAllPeersRequest) Descriptor() ([]byte, []int) {
	return file_proto_replication_proto_rawDescGZIP(), []int{12}
}

type UnmountAllPeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmountAllPeersResponse) Reset() {
	*x = UnmountAllPeersResponse{}
	mi := &file_proto_replication_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmountAllPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmountAllPeersResponse) ProtoMessage() {}

func (x *UnmountAllPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmountAllPeersResponse.ProtoReflect.Descriptor instead.
func (*UnmountAllPeersResponse) Descriptor() ([]byte, []int) {
	return file_proto_replication_proto_rawDescGZIP(), []int{13}
}

var File_proto_replication_proto protoreflect.FileDescriptor

const file_proto_replication_proto_rawDesc = "" +
	"\n" +
	"\x17proto/replication.proto\x12\vreplication\"G\n" +
	"\x1aRegisterCoordinatorRequest\x12\x19\n" +
	"\bjob_name\x18\x01 \x01(\tR\ajobName\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\"\x1d\n" +
	"\x1bRegisterCoordinatorResponse\"2\n" +
	"\x15GetCoordinatorRequest\x12\x19\n" +
	"\bjob_name\x18\x01 \x01(\tR\ajobName\"(\n" +
	"\x16GetCoordinatorResponse\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\"I\n" +
	"\x1cUnregisterCoordinatorRequest\x12\x19\n" +
	"\bjob_name\x18\x01 \x01(\tR\ajobName\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\"\x1f\n" +
	"\x1dUnregisterCoordinatorResponse\"c\n" +
	"\x19SetReplicationPeerRequest\x12)\n" +
	"\x10local_mountpoint\x18\x01 \x01(\tR\x0flocalMountpoint\x12\x1b\n" +
	"\ttarget_ip\x18\x02 \x01(\tR\btargetIp\"\x1c\n" +
	"\x1aSetReplicationPeerResponse\"B\n" +
	"\x15MountGCSBucketRequest\x12)\n" +
	"\x10local_mountpoint\x18\x01 \x01(\tR\x0flocalMountpoint\"\x18\n" +
	"\x16MountGCSBucketResponse\"?\n" +
	"\x12UnmountPeerRequest\x12)\n" +
	"\x10local_mountpoint\x18\x01 \x01(\tR\x0flocalMountpoint\"\x15\n" +
	"\x13UnmountPeerResponse\"\x18\n" +
	"\x16UnmountAllPeersRequest\"\x19\n" +
	"\x17UnmountAllPeersResponse2\xc9\x05\n" +
	"\x12ReplicationService\x12j\n" +
	"\x13RegisterCoordinator\x12'.replication.RegisterCoordinatorRequest\x1a(.replication.RegisterCoordinatorResponse\"\x00\x12[\n" +
	"\x0eGetCoordinator\x12\".replication.GetCoordinatorRequest\x1a#.replication.GetCoordinatorResponse\"\x00\x12p\n" +
	"\x15UnregisterCoordinator\x12).replication.UnregisterCoordinatorRequest\x1a*.replication.UnregisterCoordinatorResponse\"\x00\x12g\n" +
	"\x12SetReplicationPeer\x12&.replication.SetReplicationPeerRequest\x1a'.replication.SetReplicationPeerResponse\"\x00\x12[\n" +
	"\x0eMountGCSBucket\x12\".replication.MountGCSBucketRequest\x1a#.replication.MountGCSBucketResponse\"\x00\x12R\n" +
	"\vUnmountPeer\x12\x1f.replication.UnmountPeerRequest\x1a .replication.UnmountPeerResponse\"\x00\x12^\n" +
	"\x0fUnmountAllPeers\x12#.replication.UnmountAllPeersRequest\x1a$.replication.UnmountAllPeersResponse\"\x00BTZRgke-internal.googlesource.com/gke-storage/high-scale-checkpointing/lib/replicationb\x06proto3"

var (
	file_proto_replication_proto_rawDescOnce sync.Once
	file_proto_replication_proto_rawDescData []byte
)

func file_proto_replication_proto_rawDescGZIP() []byte {
	file_proto_replication_proto_rawDescOnce.Do(func() {
		file_proto_replication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_replication_proto_rawDesc), len(file_proto_replication_proto_rawDesc)))
	})
	return file_proto_replication_proto_rawDescData
}

var file_proto_replication_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_replication_proto_goTypes = []any{
	(*RegisterCoordinatorRequest)(nil),    // 0: replication.RegisterCoordinatorRequest
	(*RegisterCoordinatorResponse)(nil),   // 1: replication.RegisterCoordinatorResponse
	(*GetCoordinatorRequest)(nil),         // 2: replication.GetCoordinatorRequest
	(*GetCoordinatorResponse)(nil),        // 3: replication.GetCoordinatorResponse
	(*UnregisterCoordinatorRequest)(nil),  // 4: replication.UnregisterCoordinatorRequest
	(*UnregisterCoordinatorResponse)(nil), // 5: replication.UnregisterCoordinatorResponse
	(*SetReplicationPeerRequest)(nil),     // 6: replication.SetReplicationPeerRequest
	(*SetReplicationPeerResponse)(nil),    // 7: replication.SetReplicationPeerResponse
	(*MountGCSBucketRequest)(nil),         // 8: replication.MountGCSBucketRequest
	(*MountGCSBucketResponse)(nil),        // 9: replication.MountGCSBucketResponse
	(*UnmountPeerRequest)(nil),            // 10: replication.UnmountPeerRequest
	(*UnmountPeerResponse)(nil),           // 11: replication.UnmountPeerResponse
	(*UnmountAllPeersRequest)(nil),        // 12: replication.UnmountAllPeersRequest
	(*UnmountAllPeersResponse)(nil),       // 13: replication.UnmountAllPeersResponse
}
var file_proto_replication_proto_depIdxs = []int32{
	0,  // 0: replication.ReplicationService.RegisterCoordinator:input_type -> replication.RegisterCoordinatorRequest
	2,  // 1: replication.ReplicationService.GetCoordinator:input_type -> replication.GetCoordinatorRequest
	4,  // 2: replication.ReplicationService.UnregisterCoordinator:input_type -> replication.UnregisterCoordinatorRequest
	6,  // 3: replication.ReplicationService.SetReplicationPeer:input_type -> replication.SetReplicationPeerRequest
	8,  // 4: replication.ReplicationService.MountGCSBucket:input_type -> replication.MountGCSBucketRequest
	10, // 5: replication.ReplicationService.UnmountPeer:input_type -> replication.UnmountPeerRequest
	12, // 6: replication.ReplicationService.UnmountAllPeers:input_type -> replication.UnmountAllPeersRequest
	1,  // 7: replication.ReplicationService.RegisterCoordinator:output_type -> replication.RegisterCoordinatorResponse
	3,  // 8: replication.ReplicationService.GetCoordinator:output_type -> replication.GetCoordinatorResponse
	5,  // 9: replication.ReplicationService.UnregisterCoordinator:output_type -> replication.UnregisterCoordinatorResponse
	7,  // 10: replication.ReplicationService.SetReplicationPeer:output_type -> replication.SetReplicationPeerResponse
	9,  // 11: replication.ReplicationService.MountGCSBucket:output_type -> replication.MountGCSBucketResponse
	11, // 12: replication.ReplicationService.UnmountPeer:output_type -> replication.UnmountPeerResponse
	13, // 13: replication.ReplicationService.UnmountAllPeers:output_type -> replication.UnmountAllPeersResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_replication_proto_init() }
func file_proto_replication_proto_init() {
	if File_proto_replication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_replication_proto_rawDesc), len(file_proto_replication_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_replication_proto_goTypes,
		DependencyIndexes: file_proto_replication_proto_depIdxs,
		MessageInfos:      file_proto_replication_proto_msgTypes,
	}.Build()
	File_proto_replication_proto = out.File
	file_proto_replication_proto_goTypes = nil
	file_proto_replication_proto_depIdxs = nil
}
