// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/ranks.proto

package ranks

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Lifecycle int32

const (
	Lifecycle_PENDING   Lifecycle = 0
	Lifecycle_ASSIGNED  Lifecycle = 1
	Lifecycle_COMPLETED Lifecycle = 2
	Lifecycle_SHUTDOWN  Lifecycle = 3
)

// Enum value maps for Lifecycle.
var (
	Lifecycle_name = map[int32]string{
		0: "PENDING",
		1: "ASSIGNED",
		2: "COMPLETED",
		3: "SHUTDOWN",
	}
	Lifecycle_value = map[string]int32{
		"PENDING":   0,
		"ASSIGNED":  1,
		"COMPLETED": 2,
		"SHUTDOWN":  3,
	}
)

func (x Lifecycle) Enum() *Lifecycle {
	p := new(Lifecycle)
	*p = x
	return p
}

func (x Lifecycle) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Lifecycle) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ranks_proto_enumTypes[0].Descriptor()
}

func (Lifecycle) Type() protoreflect.EnumType {
	return &file_proto_ranks_proto_enumTypes[0]
}

func (x Lifecycle) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Lifecycle.Descriptor instead.
func (Lifecycle) EnumDescriptor() ([]byte, []int) {
	return file_proto_ranks_proto_rawDescGZIP(), []int{0}
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         Lifecycle              `protobuf:"varint,1,opt,name=state,proto3,enum=ranks.Lifecycle" json:"state,omitempty"`
	Node          string                 `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	PodUid        string                 `protobuf:"bytes,3,opt,name=pod_uid,json=podUid,proto3" json:"pod_uid,omitempty"`
	Rank          int32                  `protobuf:"varint,4,opt,name=rank,proto3" json:"rank,omitempty"`
	Jobset        string                 `protobuf:"bytes,5,opt,name=jobset,proto3" json:"jobset,omitempty"`
	JobsetShape   string                 `protobuf:"bytes,6,opt,name=jobset_shape,json=jobsetShape,proto3" json:"jobset_shape,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_proto_ranks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ranks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_ranks_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateRequest) GetState() Lifecycle {
	if x != nil {
		return x.State
	}
	return Lifecycle_PENDING
}

func (x *UpdateRequest) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *UpdateRequest) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

func (x *UpdateRequest) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *UpdateRequest) GetJobset() string {
	if x != nil {
		return x.Jobset
	}
	return ""
}

func (x *UpdateRequest) GetJobsetShape() string {
	if x != nil {
		return x.JobsetShape
	}
	return ""
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewState      Lifecycle              `protobuf:"varint,1,opt,name=new_state,json=newState,proto3,enum=ranks.Lifecycle" json:"new_state,omitempty"`
	Rank          int32                  `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"`
	ControllerIp  string                 `protobuf:"bytes,3,opt,name=controller_ip,json=controllerIp,proto3" json:"controller_ip,omitempty"`
	Jobset        string                 `protobuf:"bytes,4,opt,name=jobset,proto3" json:"jobset,omitempty"`
	JobsetShape   string                 `protobuf:"bytes,5,opt,name=jobset_shape,json=jobsetShape,proto3" json:"jobset_shape,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_proto_ranks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ranks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_proto_ranks_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateResponse) GetNewState() Lifecycle {
	if x != nil {
		return x.NewState
	}
	return Lifecycle_PENDING
}

func (x *UpdateResponse) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *UpdateResponse) GetControllerIp() string {
	if x != nil {
		return x.ControllerIp
	}
	return ""
}

func (x *UpdateResponse) GetJobset() string {
	if x != nil {
		return x.Jobset
	}
	return ""
}

func (x *UpdateResponse) GetJobsetShape() string {
	if x != nil {
		return x.JobsetShape
	}
	return ""
}

var File_proto_ranks_proto protoreflect.FileDescriptor

const file_proto_ranks_proto_rawDesc = "" +
	"\n" +
	"\x11proto/ranks.proto\x12\x05ranks\"\xb3\x01\n" +
	"\rUpdateRequest\x12&\n" +
	"\x05state\x18\x01 \x01(\x0e2\x10.ranks.LifecycleR\x05state\x12\x12\n" +
	"\x04node\x18\x02 \x01(\tR\x04node\x12\x17\n" +
	"\apod_uid\x18\x03 \x01(\tR\x06podUid\x12\x12\n" +
	"\x04rank\x18\x04 \x01(\x05R\x04rank\x12\x16\n" +
	"\x06jobset\x18\x05 \x01(\tR\x06jobset\x12!\n" +
	"\fjobset_shape\x18\x06 \x01(\tR\vjobsetShape\"\xb3\x01\n" +
	"\x0eUpdateResponse\x12-\n" +
	"\tnew_state\x18\x01 \x01(\x0e2\x10.ranks.LifecycleR\bnewState\x12\x12\n" +
	"\x04rank\x18\x02 \x01(\x05R\x04rank\x12#\n" +
	"\rcontroller_ip\x18\x03 \x01(\tR\fcontrollerIp\x12\x16\n" +
	"\x06jobset\x18\x04 \x01(\tR\x06jobset\x12!\n" +
	"\fjobset_shape\x18\x05 \x01(\tR\vjobsetShape*C\n" +
	"\tLifecycle\x12\v\n" +
	"\aPENDING\x10\x00\x12\f\n" +
	"\bASSIGNED\x10\x01\x12\r\n" +
	"\tCOMPLETED\x10\x02\x12\f\n" +
	"\bSHUTDOWN\x10\x032G\n" +
	"\fRanksService\x127\n" +
	"\x06Update\x12\x14.ranks.UpdateRequest\x1a\x15.ranks.UpdateResponse\"\x00BNZLgke-internal,googlesource.com/gke-storage/high-scale-checkpointing/lib/ranksb\x06proto3"

var (
	file_proto_ranks_proto_rawDescOnce sync.Once
	file_proto_ranks_proto_rawDescData []byte
)

func file_proto_ranks_proto_rawDescGZIP() []byte {
	file_proto_ranks_proto_rawDescOnce.Do(func() {
		file_proto_ranks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ranks_proto_rawDesc), len(file_proto_ranks_proto_rawDesc)))
	})
	return file_proto_ranks_proto_rawDescData
}

var file_proto_ranks_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_ranks_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_ranks_proto_goTypes = []any{
	(Lifecycle)(0),         // 0: ranks.Lifecycle
	(*UpdateRequest)(nil),  // 1: ranks.UpdateRequest
	(*UpdateResponse)(nil), // 2: ranks.UpdateResponse
}
var file_proto_ranks_proto_depIdxs = []int32{
	0, // 0: ranks.UpdateRequest.state:type_name -> ranks.Lifecycle
	0, // 1: ranks.UpdateResponse.new_state:type_name -> ranks.Lifecycle
	1, // 2: ranks.RanksService.Update:input_type -> ranks.UpdateRequest
	2, // 3: ranks.RanksService.Update:output_type -> ranks.UpdateResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_ranks_proto_init() }
func file_proto_ranks_proto_init() {
	if File_proto_ranks_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ranks_proto_rawDesc), len(file_proto_ranks_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ranks_proto_goTypes,
		DependencyIndexes: file_proto_ranks_proto_depIdxs,
		EnumInfos:         file_proto_ranks_proto_enumTypes,
		MessageInfos:      file_proto_ranks_proto_msgTypes,
	}.Build()
	File_proto_ranks_proto = out.File
	file_proto_ranks_proto_goTypes = nil
	file_proto_ranks_proto_depIdxs = nil
}
