// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/ranks.proto

package ranks

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RanksService_Update_FullMethodName = "/ranks.RanksService/Update"
)

// RanksServiceClient is the client API for RanksService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// gRPC service for driver instances to communicate state to the controller.
type RanksServiceClient interface {
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
}

type ranksServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRanksServiceClient(cc grpc.ClientConnInterface) RanksServiceClient {
	return &ranksServiceClient{cc}
}

func (c *ranksServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, RanksService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RanksServiceServer is the server API for RanksService service.
// All implementations should embed UnimplementedRanksServiceServer
// for forward compatibility.
//
// gRPC service for driver instances to communicate state to the controller.
type RanksServiceServer interface {
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
}

// UnimplementedRanksServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRanksServiceServer struct{}

func (UnimplementedRanksServiceServer) Update(context.Context, *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedRanksServiceServer) testEmbeddedByValue() {}

// UnsafeRanksServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RanksServiceServer will
// result in compilation errors.
type UnsafeRanksServiceServer interface {
	mustEmbedUnimplementedRanksServiceServer()
}

func RegisterRanksServiceServer(s grpc.ServiceRegistrar, srv RanksServiceServer) {
	// If the following call pancis, it indicates UnimplementedRanksServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RanksService_ServiceDesc, srv)
}

func _RanksService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RanksServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RanksService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RanksServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RanksService_ServiceDesc is the grpc.ServiceDesc for RanksService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RanksService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ranks.RanksService",
	HandlerType: (*RanksServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Update",
			Handler:    _RanksService_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ranks.proto",
}
