/*
Copyright Google 2025

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "gke-internal.googlesource.com/gke-storage/high-scale-checkpointing/apis/checkpointing.gke.io/v1"
	checkpointinggkeiov1 "gke-internal.googlesource.com/gke-storage/high-scale-checkpointing/lib/client/clientset/versioned/typed/checkpointing.gke.io/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeCheckpointConfigurations implements CheckpointConfigurationInterface
type fakeCheckpointConfigurations struct {
	*gentype.FakeClientWithList[*v1.CheckpointConfiguration, *v1.CheckpointConfigurationList]
	Fake *FakeCheckpointingV1
}

func newFakeCheckpointConfigurations(fake *FakeCheckpointingV1, namespace string) checkpointinggkeiov1.CheckpointConfigurationInterface {
	return &fakeCheckpointConfigurations{
		gentype.NewFakeClientWithList[*v1.CheckpointConfiguration, *v1.CheckpointConfigurationList](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("checkpointconfigurations"),
			v1.SchemeGroupVersion.WithKind("CheckpointConfiguration"),
			func() *v1.CheckpointConfiguration { return &v1.CheckpointConfiguration{} },
			func() *v1.CheckpointConfigurationList { return &v1.CheckpointConfigurationList{} },
			func(dst, src *v1.CheckpointConfigurationList) { dst.ListMeta = src.ListMeta },
			func(list *v1.CheckpointConfigurationList) []*v1.CheckpointConfiguration {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1.CheckpointConfigurationList, items []*v1.CheckpointConfiguration) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
